on: [push, pull_request]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: actions/cache@v4    # chache configured by setup-rust-toolchain
    #  with:
    #    path: |
    #      ~/.cargo/bin/
    #      ~/.cargo/registry/index/
    #      ~/.cargo/registry/cache/
    #      ~/.cargo/git/db/
    #      target/
    #    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy

    - name: binstall
      run: |
        [ -x /root/.cargo/bin/cargo-binstall ] || curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        [ -x /root/.cargo/bin/cargo-outdated ] || cargo binstall --no-confirm --force cargo-outdated cargo-audit cargo-pants

    - run: cargo build --release

    - run: cargo test

    - run: cargo check

    - run: cargo fmt --all -- --check

    - run: cargo clippy -- -D warnings

    - run: |
        cargo outdated
        cargo outdated --root-deps-only --exit-code 2

    - run: cargo audit

    - run: cargo pants

    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        command: check bans sources

    - uses: actions/upload-artifact@v3
      with:
        name: igotu-gt120b
        path: target/release/igotu-gt120b
