on: [push, pull_request]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: cargo-fmt, clippy, outdated, udeps, audit, pants

    - run: cargo build --release

    - run: cargo test

    - run: cargo check

    - run: cargo fmt --all -- --check

    - run: cargo clippy -- -D warnings

    - uses: EmbarkStudios/cargo-deny-action@v2

    - run: cargo outdated --exit-code 1

    - run: cargo udeps

    #- run: rm -rf ~/.cargo/advisory-db
    - run: cargo audit

    - run: cargo pants

    - uses: actions/upload-artifact@v4
      with:
        name: igotu-gt120
        path: target/release/igotu-gt120
